### ISSUE TITLE
Revisit dockerfile routine

### ISSUE THREAD

**Issue by ctorgalson** [ctorgalson/ansible-role-nextcloud-docker#35]
The j2 template for the dockerfile is now indescribably complex, but in spite of that is not easily modified for other use cases. Let's make the following changes:

1. Make the path to the template file configurable so that end-users can swap their own template in,
2. Make the default template file **more** opinionated so it lands quite close to one specific use case (e.g. proxy, redis, cron, postgres, letsencrypt, nextcloud, custom volume),
3. Provide a _single_ variable to the template, something like this:

      ```yaml
      nd_docker_compose_variables:
        cron: []
        db: []
        letsencrypt: []
        nginx: []
        redis: []
        volumes: []
      ```

    This will permit end-users to provide their _own_ variables in case their template looks quite different, while still permitting a simple and usable default configuration.
